CREATE TABLE frolf_today_courses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_name TEXT NOT NULL,
    holes INTEGER NOT NULL,
    zipcode INTEGER NOT NULL,
    latitude INTEGER NOT NULL,
    longitude INTEGER NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    rating INTEGER NOT NULL
);